# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
import os
from pathlib import Path

from Helper_test import Helper_test

class TestUploaddownload():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_uploaddownload(self):
    self.driver.get("https://demoqa.com/upload-download")
    self.driver.set_window_size(1579, 1040)

    # Fermeture des popups de pub
    ads = Helper_test.wait_for_ads_to_load(self , timeout=10)
    for ad in ads:
      self.driver.execute_script("arguments[0].remove();", ad)

    WebDriverWait(self.driver, 30).until(expected_conditions.visibility_of_element_located((By.ID, "downloadButton")))
    self.driver.find_element(By.ID, "downloadButton").click()    
    file_path = str(Path(os.path.expanduser("~\\Downloads\\sampleFile.jpeg")))
    self.driver.find_element(By.ID, "uploadFile").send_keys(file_path)



    WebDriverWait(self.driver, 30).until(expected_conditions.visibility_of_element_located((By.ID, "uploadedFilePath")))
    actions = ActionChains(self.driver)
    actions.move_to_element(self.driver.find_element(By.ID, "uploadedFilePath")).perform()
    self.driver.find_element(By.ID, "uploadedFilePath").click()

    assert "sampleFile.jpeg" in self.driver.find_element(By.ID, "uploadedFilePath").text

# if __name__ == "__main__":
#     test = TestUploaddownload()
#     test.setup_method(None)
#     try:
#         test.test_uploaddownload()
#     finally:
#         test.teardown_method(None)