# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from selenium.webdriver.common.action_chains import ActionChains

from Helper_test import Helper_test

class TestElementsTextBox():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_elementsTextBox(self):
    self.driver.get("https://demoqa.com/elements")
    self.driver.set_window_size(1600, 1040)

    # Fermeture des popups de pub
    ads = Helper_test.wait_for_ads_to_load(self , timeout=10)
    for ad in ads:
      self.driver.execute_script("arguments[0].remove();", ad)

    self.driver.find_element(By.ID, "item-0").click()
    self.driver.find_element(By.ID, "userName").click()
    self.driver.find_element(By.ID, "userName").send_keys("Simon FLORINO")
    self.driver.find_element(By.ID, "userEmail").send_keys("simon@simon.com")
    self.driver.find_element(By.ID, "currentAddress").send_keys("57 avenue de la colombe")
    self.driver.find_element(By.ID, "permanentAddress").click()
    self.driver.find_element(By.ID, "permanentAddress").send_keys("Mon adresse permanente")
    
    # Attendre que le bouton soit visible
    element = WebDriverWait(self.driver, 30).until(
      expected_conditions.visibility_of_element_located((By.ID, "submit"))
    )
    # Scroll jusqu'au bouton
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.ID, "submit").click()

    self.driver.find_element(By.CSS_SELECTOR, ".border > #permanentAddress").click()
    WebDriverWait(self.driver, 30).until(expected_conditions.visibility_of_element_located((By.CSS_SELECTOR, "#permanentAddress.mb-1")))

    assert "Simon FLORINO" in self.driver.find_element(By.ID, "name").text
    assert "simon@simon.com" in self.driver.find_element(By.ID, "email").text
    # J'utilise la selection par ID ET par class car l'ID est présent 2x dans le code
    assert "57 avenue de la colombe" in self.driver.find_element(By.CSS_SELECTOR, "#currentAddress.mb-1").text
    assert "Mon adresse permanente" in self.driver.find_element(By.CSS_SELECTOR, "#permanentAddress.mb-1").text
  
# if __name__ == "__main__":
#     test = TestElementsTextBox()
#     test.setup_method(None)
#     try:
#         test.test_elementsTextBox()
#     finally:
#         test.teardown_method(None)
