# Generated by Selenium IDE
import os
from pathlib import Path
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

from Helper_test import Helper_test

class TestForm():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_form(self):
    self.driver.get("https://demoqa.com/automation-practice-form")

    Helper_test.remove_all_google_ads(self)

    self.driver.set_window_size(1460, 1040)
    self.driver.find_element(By.ID, "firstName").click()
    self.driver.find_element(By.ID, "firstName").send_keys("Simon")
    self.driver.find_element(By.ID, "lastName").send_keys("FLORINO")
    self.driver.find_element(By.ID, "userEmail").click()
    self.driver.find_element(By.ID, "userEmail").send_keys("simon@florino.com")
    self.driver.find_element(By.CSS_SELECTOR, ".custom-radio:nth-child(1) > .custom-control-label").click()
    self.driver.find_element(By.ID, "userNumber").click()
    self.driver.find_element(By.ID, "userNumber").send_keys("0606060606")
    
    self.driver.find_element(By.ID, "dateOfBirthInput").click()
    self.driver.find_element(By.CSS_SELECTOR, ".react-datepicker__year-select").click()
    dropdown = self.driver.find_element(By.CSS_SELECTOR, ".react-datepicker__year-select")
    dropdown.find_element(By.XPATH, "//option[. = '1993']").click()
    self.driver.find_element(By.CSS_SELECTOR, ".react-datepicker__month-select").click()
    dropdown = self.driver.find_element(By.CSS_SELECTOR, ".react-datepicker__month-select")
    dropdown.find_element(By.XPATH, "//option[. = 'January']").click()
    self.driver.find_element(By.CSS_SELECTOR, ".react-datepicker__day--006:nth-child(4)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".subjects-auto-complete__value-container").click()

    time.sleep(2)
    self.driver.execute_script("window.scrollBy(0, 100);")  # scroll de 100 pixels vers le bas

    self.driver.find_element(By.ID, "subjectsInput").click()

    self.driver.find_element(By.ID, "subjectsInput").send_keys("Coucou")
    self.driver.find_element(By.CSS_SELECTOR, ".custom-checkbox:nth-child(3) > .custom-control-label").click()

    file_path = str(Path(os.path.expanduser("~\\Downloads\\Cosmic-Tango-1920-1080.jpg")))
    self.driver.find_element(By.ID, "uploadPicture").send_keys(file_path)

    time.sleep(2)
    self.driver.execute_script("window.scrollBy(0, 100);")  # scroll de 100 pixels vers le bas

    self.driver.find_element(By.ID, "subjectsInput").click()
    self.driver.find_element(By.ID, "currentAddress").click()
    self.driver.find_element(By.ID, "currentAddress").send_keys("Sur Lyon")
    self.driver.find_element(By.CSS_SELECTOR, ".css-1gtu0rj-indicatorContainer > .css-19bqh2r").click()
    self.driver.find_element(By.ID, "react-select-3-option-1").click()
    self.driver.find_element(By.CSS_SELECTOR, ".css-1pahdxg-control > .css-1hwfws3").click()
    self.driver.find_element(By.ID, "react-select-4-option-1").click()
    self.driver.find_element(By.ID, "submit").click()
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(1) > td:nth-child(1)").click()
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(2) > td:nth-child(1)").click()
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(3) > td:nth-child(1)").click()
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(4) > td:nth-child(1)").click()
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(5) > td:nth-child(1)").click()
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(6) > td:nth-child(1)").click()
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(7) > td:nth-child(1)").click()
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(8) > td:nth-child(1)").click()
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(9) > td:nth-child(1)").click()
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(10) > td:nth-child(1)").click()
    self.driver.find_element(By.ID, "closeLargeModal").click()
  
if __name__ == "__main__":
    test = TestForm()
    test.setup_method(None)
    try:
        test.test_form()
    finally:
        test.teardown_method(None)